builds:
-   ldflags:
      - -s -w
      - -extldflags "-static"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    mod_timestamp: '{{ .CommitTimestamp }}'
archives:
-   name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS
      linux: Tux
      windows: Win
    wrap_in_directory: true
    format: binary
    format_overrides:
      - goos: windows
        format: zip